### ISSUE TITLE
Create [FeaturedActivity] component

### ISSUE THREAD

**Issue by poroia** [bitprj/bit-frontend#16]
Create a component that will be used as a "featured" content for a particular page. This will need to accept dynamic props like title, description, authors, and will likely eventually need to be connected to our API, but the API part is not part of this issue.

- For this component, apart from the props, it will likely utilize the `AvatarGroup` under `src/components/shared/high` to create the avatars. See an example usage under `src/components/Student/Dashboard/Journey/Floating.js`.  This component requires names for the `AvatarGroup` which may not have been built yet. See #19.
- For the `Last Commit` part next to the star, consider using `IconLine` under `src/components/shared/low`.

![image](https://user-images.githubusercontent.com/36049897/79702827-7208c180-825c-11ea-857b-661704e933d3.png)
The component is under the `Explore`, `World`, `Activity`, and `Module` pages under Student View on the [Figma](https://www.figma.com/file/pyXHrfSlr2xx3xunNXjcpx/New-UI?node-id=0%3A1).

For now, place this component under `src/components/shared/high`

This component can be directly created in the World component. This component can be accessed through `src/components/World/World.js`. As shown in `App.js`, this component/view can be accessed by typing in the url: `/world/:id` where `:id` is equal to any number

**Comment by JersinFong** [comment]
I'm going to working on this!

**Comment by JersinFong** [comment]
![image](https://user-images.githubusercontent.com/46811144/80074417-f88ffe00-84fd-11ea-88f2-2d84b9e247b5.png)
I almost finished this component, the only issue is that icon size inside the IconLine component is fixed(1em), if I used it to render Icon, the icon size does not fit in the text size.
Should I change the Icon size or text size?

**Comment by lazyplatypus** [comment]
all the emojis need to be svgs to maintain continuity across all devices.

**Comment by lazyplatypus** [comment]
Um i think before we merge this we have to make small design changes, but just create a pull req to new-ui whenever you are ready and we can set up a meeting to merge it :)

**Comment by JersinFong** [comment]
Sure, I will do this tomorrow!
