### ISSUE TITLE
Make Reusable Action Cards

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/bit-frontend#3]
Make Reusable Action Cards that can display different content based on Passed Props using Styled Components
- [ ] ![Screenshot at Apr 12 23-49-05](https://user-images.githubusercontent.com/10321085/79099188-798a1100-7d18-11ea-9fde-856b9cc6ff9e.png)

- [ ] ![Screenshot at Apr 12 23-51-36](https://user-images.githubusercontent.com/10321085/79099241-9292c200-7d18-11ea-9b93-02c5a93da714.png)

**Comment by tomstepp** [comment]
@poroia I do I make sure to use the correct font?

**Comment by tomstepp** [comment]
**This is what I have so far:**

<img width="614" alt="Screen Shot 2020-04-18 at 8 06 18 AM" src="https://user-images.githubusercontent.com/7688478/79641318-a5a7f680-814b-11ea-8da1-68b4fad24864.png">

**Comment by poroia** [comment]
Hey Tom!

The format looks great! Right now, where are you creating these components? The font styling is global and should properly reflect on your components. Also, I noticed that your `HelpCard.js`'s onClick property was misspelled as 'onCLick', could you double check that? 

In regards to the creation of this component, there should be a reusable button that you can stick in as the button. In regards to the component's outline, you should be able to click the component on Figma and click the 'Code' bar and it'll show you some relevant CSS. In this case, it's a border of `border: 3px solid rgba(210, 210, 210, 0.2);`
